### ISSUE TITLE
Horse Stable Management software

### ISSUE THREAD

**Issue by sblankenship** [madewithangular/madewithangular.github.io#10]
Site is login.istable.com, built with Angular.js

Info about our product at www.istable.com

**Comment by lpolepeddi** [comment]
Thanks @sblankenship! Happy to add this to Made with Angular. Could you attach a 1280x711 PNG screenshot of this app after someone logs in?

**Comment by sblankenship** [comment]
Thanks!!



*From:* Lalith Polepeddi [mailto:notifications@github.com]
*Sent:* Monday, October 26, 2015 9:47 PM
*To:* madewithangular/madewithangular.github.io <
madewithangular.github.io@noreply.github.com>
*Cc:* Scott Blankenship <sblankenship@istable.com>
*Subject:* Re: [madewithangular.github.io] Horse Stable Management software
(#10)



Thanks @sblankenship <https://github.com/sblankenship>! Happy to add this
to Made with Angular. Could you attach a 1280x711 PNG screenshot of this
app after someone logs in?

—
Reply to this email directly or view it on GitHub
<https://github.com/madewithangular/madewithangular.github.io/issues/10#issuecomment-151340795>
.

**Comment by lpolepeddi** [comment]
@sblankenship I think the screenshot attachment didn't go through over email. Could you try dragging and dropping the image into [this Github issue](https://github.com/madewithangular/madewithangular.github.io/issues/10)? Thanks!

**Comment by sblankenship** [comment]
![istable dashboard](https://cloud.githubusercontent.com/assets/9343335/10819284/964c0b58-7e1d-11e5-9bbb-970ce075111e.png)

**Comment by lpolepeddi** [comment]
Thanks! Your site is up on Made with Angular - https://www.madewithangular.com/#/sites/istable
