### ISSUE TITLE
scorpapp.com

### ISSUE THREAD

**Issue by AliPoder** [madewithangular/madewithangular.github.io#112]
Scorp is the world's most friendly social network app. It has more than 2 million users and 6 million videos.

It is built with the combination of angularjs and angular material.

![adsiz](https://cloud.githubusercontent.com/assets/13220891/13028418/28a96628-d277-11e5-97a7-8c702447014e.jpg)

**Comment by lpolepeddi** [comment]
Thanks @AliPoder! Scorp is up on Made with Angular - https://www.madewithangular.com/#/sites/scorp

**Comment by AliPoder** [comment]
shouldn't it be in social category?
