### ISSUE TITLE
cryptoworld.io

### ISSUE THREAD

**Issue by Scaccomatt0** [madewithangular/madewithangular.github.io#119]
http://www.cryptoworld.io/

Built with angularjs

![screen](https://cloud.githubusercontent.com/assets/13591329/13375377/eda6be86-dd9d-11e5-9b83-d8425c4bb793.jpeg)

**Comment by lpolepeddi** [comment]
Thanks @Scaccomatt0! cryptoworld.io is up on Made with Angular https://www.madewithangular.com/#/sites/cryptoworld
