### ISSUE TITLE
https://www.progressive.com/

### ISSUE THREAD

**Issue by sudhin** [madewithangular/madewithangular.github.io#122]
Start an **Auto Quote** on the Progressive home page (https://www.progressive.com/) ...
The Progressive Direct Quoting  Application is built with Angular ( currently 1.4.*)
ScreenShot Attached ... 
![progressivedirectquoting](https://cloud.githubusercontent.com/assets/1903030/13500614/4da84ca0-e131-11e5-905a-9eeaaae4bd90.png)

**Comment by lpolepeddi** [comment]
Thanks @sudhin! Progressive is now up on Made with Angular - https://www.madewithangular.com/#/sites/progressive
