### ISSUE TITLE
Few Google Sites made w/ Angular

### ISSUE THREAD

**Issue by jasonfarrell** [madewithangular/madewithangular.github.io#124]
https://frightgeist.withgoogle.com
https://www.androidexperiments.com
https://onhubmakers.withgoogle.com
https://newslab.withgoogle.com

**Comment by lpolepeddi** [comment]
Great finds @jasonfarrell, thanks! All four sites are up on Made with Angular:

* https://www.madewithangular.com/#/sites/google-frightfest
* https://www.madewithangular.com/#/sites/android-experiments
* https://www.madewithangular.com/#/sites/onhub-makers
* https://www.madewithangular.com/#/sites/google-news-lab
