### ISSUE TITLE
Cerarmich

### ISSUE THREAD

**Issue by Crizstian** [madewithangular/madewithangular.github.io#125]
![cerarmich](https://cloud.githubusercontent.com/assets/11022466/13715925/67a4e8e4-e79d-11e5-9d37-fb14f5df7c50.png)

CERARMICH was developed with Angular 2

It's a web page about Regional made beer's from Michoacán Mexico.

<a href="http://cerarmich.org" target="_blank">Link To Cerarmich.org<a>

**Comment by lpolepeddi** [comment]
Awesome! Cerarmich is up on Made With Angular - https://www.madewithangular.com/#/sites/cerarmich
