### ISSUE TITLE
nuwait.net.kw

### ISSUE THREAD

**Issue by aymanfarhat** [madewithangular/madewithangular.github.io#126]
http://nuwait.net.kw

screenshot with the needed dimensions:

![nuwait](https://cloud.githubusercontent.com/assets/823713/13728412/0aa6fe96-e920-11e5-967c-d9d0779b42b8.jpg)

**Comment by lpolepeddi** [comment]
Thanks @aymanfarhat! Nuwait is up on Made with Angular - https://www.madewithangular.com/#/sites/nuwait
