### ISSUE TITLE
tour.vht.com

### ISSUE THREAD

**Issue by santoshjoseph99** [madewithangular/madewithangular.github.io#127]
tour.vht.com is the main page but you see anything unless you to a specific property:
http://tour.vht.com/50929659

![screen shot 2016-03-16 at 1 54 00 pm](https://cloud.githubusercontent.com/assets/461049/13828504/144315dc-eb7f-11e5-9c4c-27239e61d560.png)

**Comment by lpolepeddi** [comment]
Thanks @santoshjoseph99! @properties is up on Made with Angular - https://www.madewithangular.com/#/sites/@properties
