### ISSUE TITLE
http://vtsybulin.in.ua/

### ISSUE THREAD

**Issue by VanyaTsybulin** [madewithangular/madewithangular.github.io#130]
http://vtsybulin.in.ua/
Frontend developer portfolio

![screenshot-vtsybulin in ua](https://cloud.githubusercontent.com/assets/7935597/14065545/0bf95678-f437-11e5-9ea2-6978602f3ac1.png)

**Comment by lpolepeddi** [comment]
Cool site! Your site is up on Made with Angular - https://www.madewithangular.com/#/sites/vanya-tsybulin

**Comment by VanyaTsybulin** [comment]
Thanks @lpolepeddi )
