### ISSUE TITLE
Please add KTree.com to madewithangular.com Site

### ISSUE THREAD

**Issue by KtreeOpenSource** [madewithangular/madewithangular.github.io#134]
Thanks for the great site...It gives good insights on what can be achieved using angularJS

Can you please check our site www.KTree.com and add this site in your list, we have used the angularJS to show the case studies cads and also searching our work based on the case study tags...

We have attached the screenshot
![screencapture-ktree-com-1459887327678](https://cloud.githubusercontent.com/assets/5389600/14296954/2680c6ec-fb9a-11e5-9afd-6638bc0dc7d0.png)
 also to this issue...

Regards,
Ismail

**Comment by lpolepeddi** [comment]
Thanks @KtreeOpenSource! KTree is up on Made with Angular here - https://www.madewithangular.com/#/sites/ktree

**Comment by KtreeOpenSource** [comment]
Thanks Lalith....

I was wondering how the user will find this site browsing madewithangular homepage...I didnt find any search or any link in the home page which will redirect to https://www.madewithangular.com/#/sites/ktree , may be its there I couldn't find it...I guess you should have See All Sites for all categories somewhere in the home page so the user can come to this URL..

Regards,
Ismail

**Comment by lpolepeddi** [comment]
Thanks for the feedback! Yea, as the number of sites made with Angular have grown, the current design does not make it easy to search through them. Will think about design options.
