### ISSUE TITLE
WeFofa

### ISSUE THREAD

**Issue by amanuel2** [madewithangular/madewithangular.github.io#143]
Hello! Wefofa is the first and only forum made... Well except for [this](https://github.com/thedillonb/rails-angularjs-simple-forum) one but that one is first off made by Angular AND Ruby, and second of all is not an 'authentic forum' . Our Forum Wefofa , github page can be found here: https://github.com/amanuel2/wefofa , And website [here](http://wefofa.net16.net/)(for now, we will change website name later):   . Its still in construction and were not even close to done, because of much more features after this, but i was considering this project to go in the madewithangular.io . 

We Made This Site using:

1. HTML
2. CSS
3. JS
4. AngularJS
5. Firebase
6. AngularFire

**Comment by lpolepeddi** [comment]
Cool, keep up the good work!
