### ISSUE TITLE
http://findmore.pt/

### ISSUE THREAD

**Issue by cristianocorreia** [madewithangular/madewithangular.github.io#146]
![findmore-consulting](https://cloud.githubusercontent.com/assets/4750068/15099347/c4d9f272-154a-11e6-89ba-b4b21ead5e82.jpg)

**Comment by lpolepeddi** [comment]
Thanks @cristianocorreia! Findmore Consulting is up on Made with Angular - https://www.madewithangular.com/#/sites/findmore-consulting
