### ISSUE TITLE
wemood.co

### ISSUE THREAD

**Issue by jeandesravines** [madewithangular/madewithangular.github.io#147]
Hi,

We've created this platform which allow users to create and share moodboards through a brand new and interactive format (thanks to ng)

You can directly access to the content from  https://www.wemood.co/#/discover.

Thank you for your job. 
See you soon

Jean Desravines

**Comment by lpolepeddi** [comment]
Great! Wemood is up on Made with Angular - https://www.madewithangular.com/#/sites/wemood
