### ISSUE TITLE
wsbf.net

### ISSUE THREAD

**Issue by bentsherman** [madewithangular/madewithangular.github.io#149]
Hi, I'm the current computer engineer at WSBF-FM Clemson, and over the past school year I rewrote our website in Angular. Right now there isn't as much content as usual because we don't have many active DJs during the summer, but it's more or less complete now so I thought I'd share:

[wsbf.net](https://wsbf.net)

**Comment by lpolepeddi** [comment]
Nice! WSBF-FM Clemson is up on Made with Angular - https://www.madewithangular.com/#/sites/wsbf-fm-clemson
