### ISSUE TITLE
https://blispay.com uses angular for web and mobile hybrid apps

### ISSUE THREAD

**Issue by mhamel06** [madewithangular/madewithangular.github.io#155]
https://blispay.com uses angular for its website, iOS and android apps. 

iOS: https://itunes.apple.com/us/app/blispay-special-financing/id1069426347
Android: https://play.google.com/store/apps/details?id=com.blispay.android&hl=en

Blispay in the news: http://techcrunch.com/2016/03/31/blispay-the-financing-program-for-smbs-raises-12-75m-in-seed-funding/

We are also currently working on an updated angular2 version of the site.

**Comment by mhamel06** [comment]
![blispay-web](https://cloud.githubusercontent.com/assets/473551/16020268/33b386ee-317b-11e6-8119-ca30c37fa878.jpg)

**Comment by lpolepeddi** [comment]
@mhamel06, Great! Blispay is up on Made with Angular https://www.madewithangular.com/#/sites/blispay
