### ISSUE TITLE
http://www.kassengeist.at

### ISSUE THREAD

**Issue by SteffBi** [madewithangular/madewithangular.github.io#156]
A cash register written in angular and angular material.

You need to log into the demo to get an expression.

Do you publish german-only sites or do you know a similar listing for german sites?

![kassengeist](https://cloud.githubusercontent.com/assets/19947210/16072892/849370e2-32e3-11e6-9773-30bbddcc9634.png)

**Comment by lpolepeddi** [comment]
@SteffBi Cool! kassenGeist is up on Made with Angular - https://www.madewithangular.com/#/sites/kassengeist
