### ISSUE TITLE
https://gndf.io/

### ISSUE THREAD

**Issue by AndrewDryga** [madewithangular/madewithangular.github.io#163]
[Gandalf](https://gndf.io/) - Open Source Decision Engine

**Comment by lpolepeddi** [comment]
@AndrewDryga Cool! Could you send me a 1280x720 PNG screenshot of the app after someone logs in?

**Comment by AndrewDryga** [comment]
Yes, sure.
![2016-07-11 15 54 43](https://cloud.githubusercontent.com/assets/1877644/16731310/0a605220-4780-11e6-971d-1079c3e4bdd7.png)

**Comment by lpolepeddi** [comment]
@AndrewDryga Thanks! Gandalf is up on Made with Angular - https://www.madewithangular.com/#/sites/gandalf

**Comment by AndrewDryga** [comment]
Thanks a loot :)
