### ISSUE TITLE
https://www.coupondunia.in/ uses angular for website and app

### ISSUE THREAD

**Issue by jayaraju-gorle** [madewithangular/madewithangular.github.io#165]
Hi,

We've revamped CouponDunia website couple of months back. We've chosen to use angular.js to build our revamped website. We get 5 million monthly visits on our desktop website alone. Can you list our website under shopping category.
Here are the links
desktop version : https://www.coupondunia.in/
mobile version : https://m.coupondunia.in/
android app : https://play.google.com/store/apps/details?id=in.coupondunia.androidapp&hl=en

Thanks in advance.

**Comment by lpolepeddi** [comment]
@jayaraju-gorle Thanks! CouponDunia is up on Made with Angular - https://www.madewithangular.com/#/sites/coupondunia
