### ISSUE TITLE
https://vmatrix.org.cn

### ISSUE THREAD

**Issue by wujr5** [madewithangular/madewithangular.github.io#170]
This site is used in teaching and learning by teachers and students in [SUN YAT-SEN UNIVERSITY](http://www.sysu.edu.cn/2012/en/index.htm) from China. It is based on Angular 1.x, developing by a student team whose name is Matrix.

![image](https://cloud.githubusercontent.com/assets/7693440/18608335/1cf4b736-7d19-11e6-9708-ada894119b62.png)

**Comment by lpolepeddi** [comment]
@wujr5 Thanks! Matrix is up on Made with Angular - https://www.madewithangular.com/#/sites/matrix
