### ISSUE TITLE
OpenProject is made with Angular

### ISSUE THREAD

**Issue by lindenthal** [madewithangular/madewithangular.github.io#176]
Hi guys,

I guess OpenProject is one of the largest open source application build with AngularJS. Would be great if you could add us to your list. Please let me know if I can support you by creating a PR.

Best
Niels

**Comment by lpolepeddi** [comment]
@lindenthal Thanks! Could you attach as 1280x711 screenshot of the site after logging in?

**Comment by lindenthal** [comment]
@lpolepeddi 

Thanks for your quick response. Please find attached two screenshots. Please let me know if I can provide you any further information.

Best
Niels

![openproject-angular](https://cloud.githubusercontent.com/assets/1019287/20786379/10f143a6-b7a6-11e6-9e16-d950585bd646.jpg)
![openproject-angular_large](https://cloud.githubusercontent.com/assets/1019287/20786380/10f46c48-b7a6-11e6-8a2e-8ee76908ae5a.jpg)

**Comment by lindenthal** [comment]
@lpolepeddi

Thanks for your quick response. Please find attached the screenshot in the correct size. Please let me know if I can provide you any further information.

Best
Niels
<img width="640" alt="openproject_made-with-angular" src="https://cloud.githubusercontent.com/assets/1019287/20794534/10d522b2-b7cd-11e6-93d7-0c6f17ea5899.PNG">

**Comment by lpolepeddi** [comment]
@lindenthal Perfect! OpenProject is up on Made with Angular - https://www.madewithangular.com/#/sites/openproject
