### ISSUE TITLE
Anghami - MENA Area Lead Music Streaming Service

### ISSUE THREAD

**Issue by pierreraii** [madewithangular/madewithangular.github.io#182]
https://www.anghami.com/explore

**Comment by lpolepeddi** [comment]
Cool! Anghami is up on Made with Angular - https://www.madewithangular.com/sites/anghami

**Comment by pierreraii** [comment]
Sorry for the numerous requests - just a suggestion that Anghami is a music streaming website and could be added to the Media section of madewithangular.com, if you think it fits.

Thanks.
