### ISSUE TITLE
https://happilist.com

### ISSUE THREAD

**Issue by IbeVanmeenen** [madewithangular/madewithangular.github.io#183]
Happilist is a tool that lets you easily make gift-lists from webshops around the web.
It helps your friends choosing a gift for you and prevents the well known "double gifts trouble".
Feel free to try it out yourself 😉

I've added some screenshots below:

Homepage:
![happilist-home](https://cloud.githubusercontent.com/assets/673778/22365244/b9f38160-e476-11e6-8611-9a1f251010bf.png)

List detail:
![happilist-list](https://cloud.githubusercontent.com/assets/673778/22365248/bc66fb48-e476-11e6-96de-1427808081c1.png)

**Comment by lpolepeddi** [comment]
@IbeVanmeenen Cool! Happilist is up on Made with Angular - https://www.madewithangular.com/sites/happilist

**Comment by IbeVanmeenen** [comment]
Thanks!
