### ISSUE TITLE
http://psalter.library.uu.nl/ 

### ISSUE THREAD

**Issue by frubini** [madewithangular/madewithangular.github.io#184]
Annotated online edition of the "The Utrecht Psalter", the most valuable manuscript to be found in any Dutch collection.

![screen shot 2017-02-09 at 15 13 38](https://cloud.githubusercontent.com/assets/4182149/22786836/6a293cb0-eeda-11e6-819c-8d2d091c3c9e.png)

**Comment by lpolepeddi** [comment]
@frubini Great! Utrecht Psalter Annotated Edition has been added to Made with Angular - https://www.madewithangular.com/sites/utrecht-psalter-annotated-edition
