### ISSUE TITLE
http://papergames.io

### ISSUE THREAD

**Issue by gazeau** [madewithangular/madewithangular.github.io#186]
This is a full JS Online Game Server writen in AngularJS for the FrontEnd and NodeJS for the Backend. You can play Tic-Tac-Toe, Connect4 and Gomoku but more games are under development. 
http://papergames.io

![paper-games](https://cloud.githubusercontent.com/assets/6699040/23164830/794ca4da-f839-11e6-8b47-9205210e18f9.png)
![game-view](https://cloud.githubusercontent.com/assets/6699040/23164905/dae79240-f839-11e6-8f72-b61512f8f2ee.png)

**Comment by lpolepeddi** [comment]
@gazeau Cool! Paper Games is up on Made with Angular -
 https://www.madewithangular.com/sites/paper-games
