### ISSUE TITLE
https://www.urlaubszeit.de

### ISSUE THREAD

**Issue by westor21** [madewithangular/madewithangular.github.io#189]
Travel page in german, mainly offering cruises recommendations, using Angular in a wordpress site.

**Comment by westor21** [comment]
![fireshot screen capture 037 - urlaubszeit - kreuzfahrtzeit_ schonste zeit des jahres_ - www_urlaubszeit_de](https://cloud.githubusercontent.com/assets/1253973/23448990/76ad06fe-fe54-11e6-8d81-1cb071393824.png)

**Comment by lpolepeddi** [comment]
@westor21 Cool! Urlaubszeit is up on Made with Angular - https://www.madewithangular.com/sites/urlaubszeit

**Comment by westor21** [comment]
@lpolepeddi :-) thank you so much
