### ISSUE TITLE
https://busolinea.com

### ISSUE THREAD

**Issue by julioponce** [madewithangular/madewithangular.github.io#195]
Bus ticket seller 

![screen-shot-busolinea](https://cloud.githubusercontent.com/assets/220809/23715416/2dfb66aa-03f2-11e7-8edf-23198dcb1f59.jpg)

**Comment by lpolepeddi** [comment]
@julioponce Thanks! Busolinea is up on Made with Angular https://www.madewithangular.com/sites/busolinea
