### ISSUE TITLE
Swagger Editor 

### ISSUE THREAD

**Issue by mohsen1** [madewithangular/madewithangular.github.io#2]
It's not too large but it's a whole different kind of app that's made with AngularJS
:smile:

**Comment by mohsen1** [comment]
https://github.com/swagger-api/swagger-editor

**Comment by lpolepeddi** [comment]
Thanks for sharing this app! Could you tell me a little more about:
* How long the project has been around for
* How many monthly active users the project has
* How you're using Angular in the project

Thanks!

**Comment by mohsen1** [comment]
* I made the first commit at 2014-05-02
* 71K pageviews in last month
* Angular is used for entire project structure. From routing to rendering and splitting the code into modules. It's all Angular 1

**Comment by lpolepeddi** [comment]
Thanks @mohsen1! I've added this app to Made with Angular: https://www.madewithangular.com/#/sites/swagger-editor
