### ISSUE TITLE
App: CloudReady https://secure.exoprise.com

### ISSUE THREAD

**Issue by jblich** [madewithangular/madewithangular.github.io#200]
Made with angular, good for your tools section. I've enclosed a (fresh) screenshot too. 
If you tell me when its posted I will include a link to the page when our tools/blog post on Angular publishes.
Thanks for your help.

![cloudready dashboards screenshot](https://cloud.githubusercontent.com/assets/5677123/24874761/c6314366-1df3-11e7-8298-5d4eb0ee106a.png)

**Comment by lpolepeddi** [comment]
@jblich Thanks! Could you attach a 1280x711 PNG of the app?

**Comment by jblich** [comment]
Sure thing. It was a big screenshot. ;-) Here you go.
![madewithangularscreenshot](https://cloud.githubusercontent.com/assets/5677123/24882249/62aa82ce-1e0e-11e7-897d-5fdefcfeacd9.jpg)

**Comment by lpolepeddi** [comment]
@jblich Great! Exoprise Cloudready is up on Made with Angular - https://www.madewithangular.com/sites/exoprise-cloudready
