### ISSUE TITLE
www.timepot.io

### ISSUE THREAD

**Issue by kasiafulara** [madewithangular/madewithangular.github.io#202]
Beautiful and ergonomic time tracker written in AngularJS 2, Typescript and Java on the backend.
You can see how it works at https://timepot-demo.io (demo filled with sample data).
<img width="2560" alt="screen shot reports" src="https://cloud.githubusercontent.com/assets/11527497/25385844/93a59a40-29c5-11e7-9c1b-88ee146187cf.png">
<img width="2560" alt="screen shot timesheet" src="https://cloud.githubusercontent.com/assets/11527497/25385845/93aea2de-29c5-11e7-91f2-8638da4d2f74.png">

**Comment by lpolepeddi** [comment]
@kasiafulara Cool! Timepot is up on Made with Angular - https://www.madewithangular.com/sites/timepot
