### ISSUE TITLE
https://www.aat.org.uk (Angular 4 Universal)

### ISSUE THREAD

**Issue by modernfidelity** [madewithangular/madewithangular.github.io#203]
![aat the professional body for accounting technicians](https://cloud.githubusercontent.com/assets/306732/25430632/458f62ea-2a75-11e7-9933-ca52c580db18.png)

**Comment by lpolepeddi** [comment]
@modernfidelity Thanks! AAT is up on Made with Angular - https://www.madewithangular.com/sites/aat

**Comment by modernfidelity** [comment]
Great stuff - thank you !

**Comment by thecodecutter** [comment]
Nice one. Well done to all of those involved at AAT.
