### ISSUE TITLE
https://gemsmark.com

### ISSUE THREAD

**Issue by tamaspap** [madewithangular/madewithangular.github.io#204]
Hi guys,

We just launched our product, Gemsmark.
All our apps were built with Angular:
Homepage: https://gemsmark.com
Web App: https://app.gemsmark.com
Chrome Extension: https://chrome.google.com/webstore/detail/gemsmark/gjjlndmmfjccdaonmplmlifdadagggoi

We worked on this app for more than 2 years in our weekends and nights. Hope you'll love it, and add it to your showcase.

Cheers,
Tamas

**Comment by lpolepeddi** [comment]
@tamaspap Congrats on the launch! Gemsmark is up on Made with Angular - https://www.madewithangular.com/sites/gemsmark
