### ISSUE TITLE
https://www.thedailyproject.com

### ISSUE THREAD

**Issue by chino23** [madewithangular/madewithangular.github.io#207]
Productivity tool based on simplicity and efficiency.

![home](https://cloud.githubusercontent.com/assets/7042593/25777634/b3a381fa-3315-11e7-8b90-48ffe7e34184.png)

**Comment by lpolepeddi** [comment]
@chino23 Thanks! The Daily Project is up on Made with Angular - https://www.madewithangular.com/sites/the-daily-project

**Comment by chino23** [comment]
Thank you!
