### ISSUE TITLE
TransferWise

### ISSUE THREAD

**Issue by matteogamba** [madewithangular/madewithangular.github.io#21]
https://transferwise.com

Transfer money abroad at a fraction of the price that banks charge you.

![transferwise](https://cloud.githubusercontent.com/assets/3117946/10398774/c6265468-6ea6-11e5-9b40-42ff85e6ea83.png)

**Comment by lpolepeddi** [comment]
Thanks @matteogamba! I've added this site to Made with Angular: https://www.madewithangular.com/#/sites/transferwise
