### ISSUE TITLE
Add https://cosmunity.com/

### ISSUE THREAD

**Issue by EugeniyaKorotya** [madewithangular/madewithangular.github.io#213]
Cosmunity. Geek App for Anime, Cosplay, Comics & Gaming.

![cosmunity](https://user-images.githubusercontent.com/20662023/27856802-f36e9a96-6177-11e7-8f65-29c3f98b1efe.jpg)

**Comment by lpolepeddi** [comment]
@EugeniyaKorotya Thanks! Cosmunity is up on Made with Angular here - https://www.madewithangular.com/sites/cosmunity
