### ISSUE TITLE
https://youtube-thumbnail-viewer.firebaseapp.com/

### ISSUE THREAD

**Issue by 010pixel** [madewithangular/madewithangular.github.io#214]
Simple AngularJS based Youtube Thumbnail Viewer, useful for quick check of youtube thumbnails.

**Comment by lpolepeddi** [comment]
@010pixel Thanks! YouTube Thumbnail Viewer is up on Made with Angular - https://www.madewithangular.com/sites/youtube-thumbnail-viewer
