### ISSUE TITLE
Kickertool

### ISSUE THREAD

**Issue by hpop** [madewithangular/madewithangular.github.io#23]
Hi,
we are working for more than two years on this side project. It is a tournament software for foosball (and other sports) written in Angular. The idea was to build it without any server component so we can provide downloadable versions with nw.io. It even works offline in most browsers thanks to Application Cache.
Kickertool is available in English and German and is used in thousands of tournaments worldwide.

Website: http://kickertool.com

![en-game](https://cloud.githubusercontent.com/assets/168359/10409800/8525b068-6f36-11e5-879a-7c77c28640f4.png)

**Comment by lpolepeddi** [comment]
Thanks @hpop - cool app! I've added it to Made with Angular: https://www.madewithangular.com/#/sites/kickertool
