### ISSUE TITLE
Large Sites using Angular

### ISSUE THREAD

**Issue by DrewML** [madewithangular/madewithangular.github.io#25]
- http://www.gap.com (Checkout page(s) only)
- http://www.underarmour.com (Checkout page only)
- http://www.mapmyfitness.com/challenges/ (All "Challenges")
- http://www.bodybuilding.com/
- http://allrecipes.com/

**Comment by lpolepeddi** [comment]
Thanks @DrewML! How did you find all these sites?

I've added all the sites to Made with Angular:
* [Gap](https://www.madewithangular.com/#/sites/gap)
* [MapMyFitness](https://www.madewithangular.com/#/sites/map-my-fitness)
* [Bodybuilding.com](https://www.madewithangular.com/#/sites/bodybuilding)

Where do you see Angular on the [Under Armour checkout page](https://www.underarmour.com/en-us/cart)? Perhaps I'm missing it.

**Comment by DrewML** [comment]
@lpolepeddi I've been collecting a list for a few months as test cases when making updates to [ng-inspector](https://github.com/rev087/ng-inspector). One method I've used when hunting for new sites is the [nerdy data code search](https://search.nerdydata.com/code/). I typically just use queries with built-in directives in them (ng-repeat, ng-app, etc).

For the UA checkout page, you have to add an item to your cart (they're only using it for the actual checking out functionality).

![ua checkout](http://i.imgur.com/QsWHjcc.png)

**Comment by lpolepeddi** [comment]
Ah ok, I see Angular on the Under Armour site now. I've added Under Armour to Made with Angular: https://www.madewithangular.com/#/sites/under-armour

NerdyData's code search is pretty useful, thanks for the tip. I wish I could see more than 10 items for free!
