### ISSUE TITLE
Source Code Statistics

### ISSUE THREAD

**Issue by nsmgr8** [madewithangular/madewithangular.github.io#279]
I have built a source code statistics viewer with angular. The code is available on github https://github.com/nsmgr8/git-stats/ and a deployment can be found here https://nsmgr8.github.io/git-stats-demo/#/

I would love to see it listed in made-with-angular site.

Thanks.

**Comment by lpolepeddi** [comment]
Thanks! Source Code Statistics is up on Made with Angular - https://www.madewithangular.com/sites/source-code-statistics
