### ISSUE TITLE
Broadband and mobile deals grid

### ISSUE THREAD

**Issue by tgregan90** [madewithangular/madewithangular.github.io#284]
https://www.broadbandchoices.co.uk/broadband/best-deals 
https://www.broadbandchoices.co.uk/mobile/phone-deals/contracts
Currently using Angular version 1.6.8

**Comment by lpolepeddi** [comment]
Thanks for sharing. Where do you see Angular being used on this site?

**Comment by lpolepeddi** [comment]
@tgregan90 Thanks! broadbandchoices is up on Made with Angular - https://www.madewithangular.com/sites/broadbandchoices
