### ISSUE TITLE
Made with Angular 6 Universal

### ISSUE THREAD

**Issue by aparraga** [madewithangular/madewithangular.github.io#290]
Hi,

Please check it out: https://eltocadordecarlota.com
It's a 100% angular 6 universal, SEO friendly commence platform built from the scratch.
Angular's server side rendering it's a great feature that allow us to serve different products from different URLS being 100% SEO friendly and accelerates the user waiting time by downloading the already rendered version to the end user.
I think that this website fit perfectly with your audience as a clear example of Angular built website, it could be great to us to see the site published in Made With Angular.

Thank you!

**Comment by aparraga** [comment]
Now it has been ported to Angular 7. 
Please also check this other guy: https://jochefina.com (also made with Angular 7 universal).
Do you think that you could consider including both in your website?

**Comment by esobczak1970** [comment]
Anyone have any luck with getting good scores on Pagespeed Insights?

**Comment by lpolepeddi** [comment]
Thanks! Both sites are up on Made with Angular:
* https://www.madewithangular.com/sites/el-tocador-de-carlota
* https://www.madewithangular.com/sites/jochefina
