### ISSUE TITLE
Add Taskify, made with Angular 6

### ISSUE THREAD

**Issue by Aveek-Saha** [madewithangular/madewithangular.github.io#298]
Taskify is a group task sharing website created with Angular 6 and Firebase
link: https://taskify.aveek.io
GitHub: https://github.com/Aveek-Saha/Taskify

**Comment by Aveek-Saha** [comment]
# Here are a few screenshots
## Group tasks
![group-screenshot](https://user-images.githubusercontent.com/31800695/50411830-4113aa80-0829-11e9-9ac4-af6fd0a4ca0b.png)

## List of groups
![list-of-groups](https://user-images.githubusercontent.com/31800695/50411853-76b89380-0829-11e9-95e5-e8fc32503b91.png)

## Personal tasks

![personal-task-list](https://user-images.githubusercontent.com/31800695/50411859-8506af80-0829-11e9-9597-679c8fefd71d.png)

**Comment by lpolepeddi** [comment]
Great! Taskify is up on Made with Angular - https://www.madewithangular.com/sites/taskify
