### ISSUE TITLE
LingoHub App

### ISSUE THREAD

**Issue by lpsBetty** [madewithangular/madewithangular.github.io#3]
Our whole web app is made with Angular!
Link: https://translate.lingohub.com/

More infos about LingoHub: https://lingohub.com/

**Comment by lpolepeddi** [comment]
Thanks for sharing this app! Could you tell me a little more about:
* How long the project has been around for
* How many monthly active users the project has
* How you're using Angular in the project

Thanks!

**Comment by lpsBetty** [comment]
* Since 2012
* around 2000
* our complete frontend app is written in AngularJS 1.4 - amongst other things we offer an online editor for an easy and efficient translation of text segments - it is full of features like text suggestions, text autocomplete or shortcuts etc.
