### ISSUE TITLE
BMW Australia dealer Locator and driveAwayPrice.

### ISSUE THREAD

**Issue by peterhe2000** [madewithangular/madewithangular.github.io#304]
Open bmw.com.au.
On the top menu, click 'buying'.
Then on the bottom right got two button 'Find a BMW Dealer' to navigate to dealer locator and 'Driveaway Calculator' to navigate to Drive Away Price.
Both SPA application developed by Angular 6.

**Comment by lpolepeddi** [comment]
Thanks! Both sites are now up on Made with Angular:
* https://www.madewithangular.com/sites/bmw-find-a-dealer
* https://www.madewithangular.com/sites/bmw-driveaway-price-calculator
