### ISSUE TITLE
This site looks awesome and It's done in Angular 7 with Angular universal

### ISSUE THREAD

**Issue by tibinthomas** [madewithangular/madewithangular.github.io#314]
Hi,

Can you add this website which is entirely built in Angular 7 & Angular Universal

Please have a look at this:
https://www.infinijith.com/

Thanks

**Comment by lpolepeddi** [comment]
@tibinthomas Thanks! Infinijith is up on Made with Angular - https://www.madewithangular.com/sites/infinijith

Closes #315
