### ISSUE TITLE
Built this with Angular 7, Bootstrap CSS, Material Design with lots of love - Check it out

### ISSUE THREAD

**Issue by akmirge** [madewithangular/madewithangular.github.io#317]
Built this with Angular 7, Bootstrap CSS, Material Design with lots of love - https://akmirge.github.io/ Let me know if you are able to add this to your made with angular list.

**Comment by lpolepeddi** [comment]
Thanks! Sri Sai Satcharitra is up on Made with Angular - https://www.madewithangular.com/sites/sri-sai-satcharitra

**Comment by akmirge** [comment]
Thank you!

Anil
