### ISSUE TITLE
https://codverter.com

### ISSUE THREAD

**Issue by Jonathan435** [madewithangular/madewithangular.github.io#318]
**CodVerter** was created for developers by developers and is entirely made  with angular 4 and uses many features of angular.

After long 2 years of development we are finally online and in the coming year we will upgrade the application to angular 7.

 You are welcome to explore [CodVerter ](https://codverter.com/src/index)and if you find it suitable for "made with angular"  list we will be grateful for adding us to your list.

![indexpage](https://user-images.githubusercontent.com/7534264/52902549-decc9a00-321a-11e9-9070-a5672043ac53.PNG)

**Comment by lpolepeddi** [comment]
Thanks! Codverter is up on Made with Angular - https://www.madewithangular.com/sites/codverter
