### ISSUE TITLE
myodds.bet

### ISSUE THREAD

**Issue by EdWood1994** [madewithangular/madewithangular.github.io#319]
Hi, check the page [https://www.myodds.bet](https://www.myodds.bet). It's made with Angular 6.1 + Angular Design. Website provides odds comparison services and features for esports. The page is highly interactive and uses all features from Angular. Please, check the help section to get better idea how the website works. Thank you!

**Comment by lpolepeddi** [comment]
Thanks! Myodds.bet is up on Made with Angular - https://www.madewithangular.com/sites/myodds-bet
