### ISSUE TITLE
Traduora - translation management platform for teams

### ISSUE THREAD

**Issue by anthonynsimon** [madewithangular/madewithangular.github.io#321]
Traduora is a translation management platform for teams. Once you setup your project you can import and export your translations to various formats, work together with your team, instantly deliver translation updates over the air, and soon automatically translate your project via third-party integrations.

Our stack is Typescript in the frontend (Angular 7) and in the backend (Nest.js + Express).

GitHub repo: https://github.com/traduora/traduora
Homepage: https://traduora.com

![Traduora product screenshot](https://traduora.com/static/media/traduora-preview.de331275.png)

**Comment by lpolepeddi** [comment]
Thanks! Traduora is up on Made with Angular - https://www.madewithangular.com/sites/traduora
