### ISSUE TITLE
Loan calculator: https://ej2.syncfusion.com/showcase/angular/loancalculator/

### ISSUE THREAD

**Issue by suresh-mohan** [madewithangular/madewithangular.github.io#329]
Loan Calculator: https://ej2.syncfusion.com/showcase/angular/loancalculator/

was developed using Angular 5

**Comment by lalithpolepeddi** [comment]
Thanks for your contribution! As mentioned in #327, please consider [sharing your project in this discussion](https://github.com/madewithangular/madewithangular.github.io/discussions/432) - thank you!
