### ISSUE TITLE
Diagram Builder: https://ej2.syncfusion.com/showcase/angular/diagrambuilder/

### ISSUE THREAD

**Issue by suresh-mohan** [madewithangular/madewithangular.github.io#330]
Diagram Builder: https://ej2.syncfusion.com/showcase/angular/diagrambuilder/

was developed using Angular 5

**Comment by lalithpolepeddi** [comment]
Thanks for your contribution! As mentioned in #327, please consider [sharing your project in this discussion](https://github.com/madewithangular/madewithangular.github.io/discussions/432) - thank you!
