### ISSUE TITLE
Add https://kuindzhi-eng.tretyakov.ru

### ISSUE THREAD

**Issue by Dok11** [madewithangular/madewithangular.github.io#336]
URL: https://kuindzhi-eng.tretyakov.ru/
Version: 6.1.8
Category: Education

![ng-kuindzhi-6 1 8](https://user-images.githubusercontent.com/2697890/57710286-49a03c80-7675-11e9-83d9-e890753dda9e.jpg)

**Comment by lalithpolepeddi** [comment]
Thank you for your contribution! As mentioned in #332, please consider [sharing your project in this discussion](https://github.com/madewithangular/madewithangular.github.io/discussions/432) - thank you!
