### ISSUE TITLE
Add http://elt.tech/

### ISSUE THREAD

**Issue by Dok11** [madewithangular/madewithangular.github.io#337]
URL: http://elt.tech/
Version: 6.0.9
Category: Entertainment

![ng-elt-6 0 9](https://user-images.githubusercontent.com/2697890/57710447-a69bf280-7675-11e9-85f0-00faa2b79f87.jpg)

**Comment by lalithpolepeddi** [comment]
Thank you for your contribution! Similar to #334, we were unable to load your project. If you have any new projects, please consider [sharing your project in this discussion](https://github.com/madewithangular/madewithangular.github.io/discussions/432) - thank you!
