### ISSUE TITLE
Add https://fabrikant.su/

### ISSUE THREAD

**Issue by Dok11** [madewithangular/madewithangular.github.io#338]
URL: https://fabrikant.su/
Version: 1.5.8
Category: Entertainment

![ng-fabrikant-1 5 8](https://user-images.githubusercontent.com/2697890/57710689-1611e200-7676-11e9-95ee-377d72722321.jpg)

**Comment by lalithpolepeddi** [comment]
Thank you for your contribution! As mentioned in #332, please consider [sharing your project in this discussion](https://github.com/madewithangular/madewithangular.github.io/discussions/432) - thank you!
