### ISSUE TITLE
Add http://grainholding.ru

### ISSUE THREAD

**Issue by Dok11** [madewithangular/madewithangular.github.io#339]
URL: http://grainholding.ru/
Version: 5.2.1
Category: Entertainment

![ng-grainholding-5 2 1](https://user-images.githubusercontent.com/2697890/57710905-756ff200-7676-11e9-9dde-82205fdee0b1.jpg)

**Comment by lalithpolepeddi** [comment]
Thank you for your contribution! As mentioned in #332, please consider [sharing your project in this discussion](https://github.com/madewithangular/madewithangular.github.io/discussions/432) - thank you!
