### ISSUE TITLE
Add https://www.samsung-forward.ru

### ISSUE THREAD

**Issue by Dok11** [madewithangular/madewithangular.github.io#340]
URL: https://www.samsung-forward.ru/
Version: 6.1.2
Category: Entertainment

![ng-samsung-forward-6 1 2](https://user-images.githubusercontent.com/2697890/57711142-df889700-7676-11e9-9e7b-1ebdbb23685f.jpg)

**Comment by lalithpolepeddi** [comment]
@DareBoost Thanks! Samsung Forward is up on Made with Angular - https://www.madewithangular.com/sites/samsung-forward
