### ISSUE TITLE
Showcased website "google pay" is not displaying as angular application.

### ISSUE THREAD

**Issue by sourabh09** [madewithangular/madewithangular.github.io#361]
Showcased website google pay is not displaying as angular application. I have tried to figured out with wappalyzer chrome extension and I have also enter and hit "angular" in browser console I am not getting any object [With child objects as "bind","bootstrap","callbacks","module" etc.]
![2019-09-10_1514](https://user-images.githubusercontent.com/26563763/64603313-d2d63e80-d3dd-11e9-8c2b-a1dad02adad1.png)

**Comment by lalithpolepeddi** [comment]
@sourabh09 Looks like Google Pay moved away from Angular. Removed the site from Made with Angular. Thanks for letting us know.
