### ISSUE TITLE
https://semdo.de/app/#/

### ISSUE THREAD

**Issue by mrdevin** [madewithangular/madewithangular.github.io#37]
suggested site

**Comment by lpolepeddi** [comment]
Thanks @mrdevin! Happy to add this to Made with Angular. Could you attach a 1280x711 PNG screenshot of this app after someone logs in?

**Comment by mrdevin** [comment]
![screen shot 2015-11-03 at 18 44 47](https://cloud.githubusercontent.com/assets/864287/10916310/27a585d4-825b-11e5-9b23-db2f10b9a983.png)

Thanks @lpolepeddi

**Comment by lpolepeddi** [comment]
Thanks! Your site is up on Made With Angular - https://www.madewithangular.com/#/sites/semdo
