### ISSUE TITLE
Honest Beauty

### ISSUE THREAD

**Issue by jonricaurte** [madewithangular/madewithangular.github.io#39]
honestbeauty.com used angular for the whole site

**Comment by jonricaurte** [comment]
![screen shot 2015-11-04 at 5 29 54 pm](https://github-cloud.s3.amazonaws.com/assets%2F1715240%2F10957507%2Fd06310b0-8319-11e5-8300-34ba2d29b8ca.png)

**Comment by lpolepeddi** [comment]
Thanks @jonricaurte! Honest Beauty is now on Made with Angular https://www.madewithangular.com/#/sites/honest-beauty

**Comment by jonricaurte** [comment]
@lpolepeddi thanks!
