### ISSUE TITLE
www.vamosio.com

### ISSUE THREAD

**Issue by chet28** [madewithangular/madewithangular.github.io#40]
http://www.vamosio.com A travel bucket list site with photos, facts, maps, etc. on the ultimate destinations in the world. Uses angularjs throughout the entire site.
![Alt text](https://scontent-lhr3-1.xx.fbcdn.net/hphotos-xlt1/v/t1.0-9/11695990_503502983152113_7970202009631975862_n.jpg?oh=657b8c93413965e215bbae8229d3ecf9&oe=56C1C30B)

**Comment by lpolepeddi** [comment]
Thanks @chet28! Vamosio is now on Made with Angular - https://www.madewithangular.com/#/sites/vamosio

**Comment by chet28** [comment]
Thanks Lalith,

Any chance it can be included in the “Travel and Local” category?

Regards
Chet
