### ISSUE TITLE
https://egov.maryland.gov/msp/vsi

### ISSUE THREAD

**Issue by freedomab** [madewithangular/madewithangular.github.io#42]
State of Maryland Vehicle Safety Inspection is developed from a ground up using AngularJS 1.*

**Comment by freedomab** [comment]
![vsi](https://cloud.githubusercontent.com/assets/15878406/11194862/94a85ca8-8c7c-11e5-9c4a-50b1459568ba.PNG)

**Comment by lpolepeddi** [comment]
Thanks @freedomab! The site is up on Made with Angular - https://www.madewithangular.com/#/sites/maryland-state-police
