### ISSUE TITLE
Site Suggestion - KLM

### ISSUE THREAD

**Issue by ala-ebi** [madewithangular/madewithangular.github.io#427]
https://www.klm.com/
Uses Angular 14+

**Comment by lalithpolepeddi** [comment]
Nice find! We've added KLM to the showcase on our [new website](https://www.madewithangular.com).

If you have any new projects made with Angular, please consider [sharing them in this discussion](https://github.com/madewithangular/madewithangular.github.io/discussions/432)! The discussion provides an opportunity for the community to see, appreciate, and discuss your work - thank you!
