### ISSUE TITLE
Noodlio - A marketplace for app development

### ISSUE THREAD

**Issue by noodlio** [madewithangular/madewithangular.github.io#46]
Browse and submit high-quality themes, templates and components for apps on www.noodl.io

![post_madewithangular_1280](https://cloud.githubusercontent.com/assets/15873906/11302020/b55b456e-8f92-11e5-97bc-e6e0c4cb4f2f.png)

**Comment by lpolepeddi** [comment]
Thanks! Noodlio is now on Made with Angular https://www.madewithangular.com/#/sites/noodlio
