### ISSUE TITLE
moozvine.com

### ISSUE THREAD

**Issue by richmartin** [madewithangular/madewithangular.github.io#47]
[Moozvine](https://www.moozvine.com) has a web frontend built fully in AngularJS.

The site provides SciFi ebooks from highly-acclaimed authors under a Creative Commons licence with a Pay-What-You-Want model and Threshold-Release model that allows the public to support the authors as much or as little as they want while still being able to freely download, read and share the books.

The site launched a couple of months ago and already has some very high-profile authors on-board, including two of this year's Hugo-award winners and winners of Hugos and other awards from previous years.

![moozvine-screenshot](https://cloud.githubusercontent.com/assets/5993015/11362629/41a01b26-9295-11e5-921c-9fb2acd764e6.png)

**Comment by lpolepeddi** [comment]
Thanks @richmartin! Moozvine is up on Made with Angular https://www.madewithangular.com/#/sites/moozvine

**Comment by richmartin** [comment]
Thanks for that.

Do you think you could move it to the Books & Reference category?
