### ISSUE TITLE
http://app.trendingdevs.com/

### ISSUE THREAD

**Issue by shprink** [madewithangular/madewithangular.github.io#50]
http://app.trendingdevs.com

Angular 1.4.x and Angular Material.

Created by myself. 

Twitter of the app: https://twitter.com/Trending_Devs
Mine: https://twitter.com/julienrenaux

Cheers,
Julien

**Comment by lpolepeddi** [comment]
Thanks @shprink! TrendingDevs is up on Made with Angular - https://www.madewithangular.com/#/sites/trending-devs

**Comment by shprink** [comment]
Great thanks very much!
