### ISSUE TITLE
mysolarcity.com

### ISSUE THREAD

**Issue by gdi2290** [madewithangular/madewithangular.github.io#54]
https://mysolarcity.com/ uses angular

**Comment by lpolepeddi** [comment]
Thanks @gdi2290. Do you have 1280x711 PNG screenshot of this page after someone logs in?

**Comment by gdi2290** [comment]
you probably have to resize it
![screen shot 2015-11-28 at 5 00 06 pm](https://cloud.githubusercontent.com/assets/1016365/11454808/82a5cbac-95f1-11e5-9500-90ec4a86972d.jpg)

**Comment by lpolepeddi** [comment]
Thanks for this @gdi2290. Solar City is up on Made with Angular - https://www.madewithangular.com/#/sites/solar-city
