### ISSUE TITLE
lyft uses angular

### ISSUE THREAD

**Issue by gdi2290** [madewithangular/madewithangular.github.io#57]
https://www.lyft.com/ uses angular

**Comment by lpolepeddi** [comment]
Thanks @gdi2290! Lyft is up on Made with Angular - https://www.madewithangular.com/#/sites/lyft

**Comment by gdi2290** [comment]
I would tweet about this company

**Comment by lpolepeddi** [comment]
Yep, planning on tweeting about all the companies you submitted. Thanks
again!

**Comment by gdi2290** [comment]
no problem :+1:  we should work on making an ng2 version with pre-rendered views next year ;)

**Comment by lpolepeddi** [comment]
Agreed. I'll add it to the list!
