### ISSUE TITLE
www.scion.com/build-your-scion

### ISSUE THREAD

**Issue by gdi2290** [madewithangular/madewithangular.github.io#60]
https://www.scion.com/build-your-scion uses angular

**Comment by lpolepeddi** [comment]
Thanks @gdi2290! Build Your Scion is up on Made with Angular - https://www.madewithangular.com/#/sites/build-your-scion.

How did you find all of these?

**Comment by gdi2290** [comment]
I went through a fortune 500 list and startup unicorn list then checked the landing page or any login pages looking for [ng-detector](https://chrome.google.com/webstore/detail/ng-detector/fedicaemhcfcmelihceehhaodggfeffm?hl=en) to trigger. I went through them quickly to see any brands that I knew about so I didn't go through them all

**Comment by lpolepeddi** [comment]
That's smart. Did you do this manually or did you have a crawler?

**Comment by gdi2290** [comment]
manually, making a crawler would be a better idea since you can keep track of the existing websites and websites on these lists

**Comment by lpolepeddi** [comment]
Cool, thanks for sharing your method.

@DrewML [shared here](https://github.com/madewithangular/madewithangular.github.io/issues/25#issuecomment-151347352) that he finds sites made with AngularJS using [NerdyData's code search tool](https://search.nerdydata.com/code/). Unfortunately you can't see more than 10 sites for free, but regardless a cool way to find AngularJS sites.
