### ISSUE TITLE
My PT Hub

### ISSUE THREAD

**Issue by adcuz** [madewithangular/madewithangular.github.io#64]
My PT Hub is made with angular: https://www.mypthub.net/
Category: Health & Fitness

![mypthub](https://cloud.githubusercontent.com/assets/244424/11476593/8fb1e606-977b-11e5-81a1-5525ac30f641.png)

**Comment by lpolepeddi** [comment]
Thanks @adcuz! My PT Hub is up on Made with Angular - https://www.madewithangular.com/#/sites/my-pt-hub
