### ISSUE TITLE
overEducate

### ISSUE THREAD

**Issue by karimjamal** [madewithangular/madewithangular.github.io#67]
http://www.overeducate.com/ is built from the ground up using Angular. It's purpose it to aid people in finding the most efficient educational path towards their desired career.

![overeducate](https://cloud.githubusercontent.com/assets/5757857/11582803/6301668c-9a18-11e5-866c-32a4b19f0a4b.png)

**Comment by lpolepeddi** [comment]
Thanks @karimjamal! overEducate is up on Made with Angular https://www.madewithangular.com/#/sites/overeducate

**Comment by karimjamal** [comment]
Thanks @lpolepeddi! Much appreciated. Would it be possible to also include the site in the Education category (https://www.madewithangular.com/#/categories/education)?
