### ISSUE TITLE
app.skveege.com

### ISSUE THREAD

**Issue by michaelkrog** [madewithangular/madewithangular.github.io#68]
The app part of [Skveege](http://skveege.com) is built up in Angular + Angular Material.
It is an automatic route planner for Window Cleaners.

![skveege-screenshot](https://cloud.githubusercontent.com/assets/681472/11608266/af51557c-9b64-11e5-80e1-2411835eabb7.png)

**Comment by lpolepeddi** [comment]
Thanks @michaelkrog! Skveege is up on Made with Angular - https://www.madewithangular.com/#/sites/skveege
