### ISSUE TITLE
managewp.com

### ISSUE THREAD

**Issue by Kouteki** [madewithangular/madewithangular.github.io#72]
The ManageWP members dashboard is built with Angular. The category could be Productivity, Tools or Business (in that order).
Here's a 1280x711 PNG screenshot of the dashboard.
![managewp orion](https://cloud.githubusercontent.com/assets/12710860/11840115/7cc4dd30-a3f3-11e5-9246-ce73db7f4dc7.png)

**Comment by lpolepeddi** [comment]
Thanks @Kouteki! ManageWP is up on Made with Angular - https://www.madewithangular.com/#/sites/managewp
