### ISSUE TITLE
New suggestion

### ISSUE THREAD

**Issue by gzamboni** [madewithangular/madewithangular.github.io#73]
https://app.jetbov.com

**Comment by lpolepeddi** [comment]
Thanks @gzamboni! Could you attach a 1280x711 screenshot of this app after someone logs in?

**Comment by gzamboni** [comment]
@lpolepeddi as you wish: :)

![jetbov_-_dashboard](https://cloud.githubusercontent.com/assets/617715/12456300/52336a2e-bf86-11e5-9ea1-e5940b46b3c0.png)

Thanks

**Comment by lpolepeddi** [comment]
Perfect. JetBov is up on Made with Angular - https://www.madewithangular.com/#/sites/jetbov
