### ISSUE TITLE
metocat.com

### ISSUE THREAD

**Issue by annatomka** [madewithangular/madewithangular.github.io#78]
Our site https://metocat.com is built with AngularJS. It's a webapp where you can create simple voting forms, see realtime statistics about the votings and share forms on Twitter. 

![metocat_preview_1280x711](https://cloud.githubusercontent.com/assets/2573711/11879803/d7274a5a-a4fd-11e5-9ff4-7210cfa07d1a.png)

**Comment by lpolepeddi** [comment]
Thanks @annatomka! MetoCat is up on Made with Angular - https://www.madewithangular.com/#/sites/metocat
