### ISSUE TITLE
Tagpacker

### ISSUE THREAD

**Issue by cnmuc** [madewithangular/madewithangular.github.io#8]
Tagpacker - a free tool to organize, find and share your favourite links. 
http://tagpacker.com

**Comment by lpolepeddi** [comment]
Thanks @cnmuc! Happy to add this to Made with Angular. Could you attach a 1280x711 PNG screenshot of this app after someone logs in?

**Comment by cnmuc** [comment]
![tagpacker-profile-1280x711](https://cloud.githubusercontent.com/assets/4402945/10820960/29ffb0c0-7e50-11e5-8413-bff20f85d815.png)

**Comment by lpolepeddi** [comment]
Thanks! Your site is now up on Made with Angular - https://www.madewithangular.com/#/sites/tagpacker
