### ISSUE TITLE
ILTER

### ISSUE THREAD

**Issue by Crizstian** [madewithangular/madewithangular.github.io#83]
![captura de pantalla 2015-12-21 a las 6 39 03 p m](https://cloud.githubusercontent.com/assets/11022466/11945145/26f8f8f0-a812-11e5-8734-d40a0794f10e.png)

<strong>This app was developed as tool for scientist's around 30 country's</strong>,
that studies the Atmosphere ecosystem, this app can create 
<ul><li>charts</li><li> show maps</li><li>create scatter graphs</li><li> and provide full information of a particular site using modals</li></ul>
using the filters and search tools site, also is a CRUD app for maintaining the information for the scientist.

<a href="http://132.248.172.188" target="_blank">CLICK HERE TO VIST ILTER APP SITE</a>

**Comment by lpolepeddi** [comment]
Thanks @Crizstian! ILTER is up on Made with Angular - https://www.madewithangular.com/#/sites/ilter
