### ISSUE TITLE
Swedbank Online banking

### ISSUE THREAD

**Issue by Evanion** [madewithangular/madewithangular.github.io#85]
https://online.swedbank.se
This is the new online banking client for the Swedish bank 'Swedbank'. It's still in beta. But looks promising.

**Comment by lpolepeddi** [comment]
Cool! Could you attach a 1280x711 screenshot of the app after someone logs in?

**Comment by Evanion** [comment]
https://www.dropbox.com/s/3d6gv42i0ax5nqn/Screenshot%202015-12-31%2019.04.32.png?dl=0
The information in the screenshot is anonymised.

**Comment by lpolepeddi** [comment]
Thanks! Swedbank is up on Made with Angular - https://www.madewithangular.com/#/sites/swedbank
