### ISSUE TITLE
App Credit Card Admin

### ISSUE THREAD

**Issue by cooper1388** [madewithangular/madewithangular.github.io#86]
This is an AngujarJs + AngularMaterial Android App for Credit Card Management, so I thought to show it here at madewithangular.

https://play.google.com/store/apps/details?id=com.hn.coopersoft.creditcardapp

Thanks.

**Comment by lpolepeddi** [comment]
Thanks @cooper1388! Credit Card Admin is up on Made with Angular - https://www.madewithangular.com/#/sites/credit-card-admin
