### ISSUE TITLE
Alpha Bank Greece

### ISSUE THREAD

**Issue by predatorkill** [madewithangular/madewithangular.github.io#87]
Alpha Bank Greece has switched to AngularJS few months ago

Although the front end is using CommonJS when you are logged in it uses AngularJS https://www.alpha.gr/e-banking

**Comment by lpolepeddi** [comment]
Cool! Could you attach a 1280x711 JPG screenshot of the app after someone logs in?

**Comment by predatorkill** [comment]
Sure, there you go!

![alpha_bank_greece](https://cloud.githubusercontent.com/assets/717975/12070434/1b831ac8-b07d-11e5-9e24-fda68d40c8da.png)

**Comment by lpolepeddi** [comment]
Thanks! Alpha Bank is up on Made with Angular https://www.madewithangular.com/#/sites/alpha-bank
