### ISSUE TITLE
eyeopen.nl

### ISSUE THREAD

**Issue by izelnakri** [madewithangular/madewithangular.github.io#89]
https://www.eyeopen.nl and also https://blog.eyeopen.nl they use the same css and js.

**Comment by lpolepeddi** [comment]
Thanks @izelnakri! Could you attach a 1280x711 JPG screenshot after someone logs in?

**Comment by izelnakri** [comment]
<img width="1280" alt="online_hypotheekadvies" src="https://cloud.githubusercontent.com/assets/1190931/12182494/cd40c516-b588-11e5-809b-95ff1ee60e9f.png">

**Comment by lpolepeddi** [comment]
Thanks! eyeOpen.nl is up on Made with Angular https://www.madewithangular.com/#/sites/eyeopen
