### ISSUE TITLE
Ennomotive App

### ISSUE THREAD

**Issue by fauria** [madewithangular/madewithangular.github.io#9]
Ennomotive App, used to manage innovation challenges, is made with Angular (MEAN stack): https://app.ennomotive.com

Main website: https://www.ennomotive.com/

**Comment by lpolepeddi** [comment]
Thanks @fauria! Happy to add this to Made with Angular. Could you attach a 1280x711 screenshot of this app after someone logs in?

**Comment by fauria** [comment]
Sure! Here it is:

http://i.imgur.com/kdgytZT.png

Regards

**Comment by lpolepeddi** [comment]
Thanks @fauria! The site is up on Made with Angular: https://www.madewithangular.com/#/sites/ennomotive
