### ISSUE TITLE
loadingspot.com

### ISSUE THREAD

**Issue by andrejkosyak** [madewithangular/madewithangular.github.io#91]
loadingspot.com is logistics database. built 100% on Angular and jQuery

**Comment by lpolepeddi** [comment]
Thanks @andrejkosyak! Could you attach a 1280x711 JPG screenshot of the app after someone logs in?

**Comment by andrejkosyak** [comment]
![loadingspot_angular](https://cloud.githubusercontent.com/assets/6382243/12674403/1a61aaf8-c683-11e5-84a1-1a72ab2ab92c.jpg)

**Comment by lpolepeddi** [comment]
Thanks! LoadingSpot is on Made with Angular - https://www.madewithangular.com/#/sites/loading-spot
