### ISSUE TITLE
sisense.com

### ISSUE THREAD

**Issue by motigra** [madewithangular/madewithangular.github.io#94]
Hi,
I'd like to add Sisense (http://www.sisense.com/) to your list!
We're a BI product installed on-premise at several hundred (big) customers, and our user-facing application is a web app built on Angular 1.4 (with node and mongo at the back).
We've been using Angular as our main framework for over 2 years - every bit of our UI uses it!

You can see a screenshot of how a dashboard looks here: http://prntscr.com/9p5nwu (taken from our online demo)

Thanks! 
- Moti

**Comment by lpolepeddi** [comment]
Thanks @motigra! Sisense is up on Made with Angular - https://www.madewithangular.com/#/sites/sisense
