### ISSUE TITLE
TransferXL.com

### ISSUE THREAD

**Issue by ramondeklein** [madewithangular/madewithangular.github.io#95]
[TransferXL](https://transferxl.com) is a 100% AngularJS website. It's a next generation file transfer site that depends fully on client-side scripting and uses AngularJS at its main framework. It uses AngularJS to provide the end-user a beautiful, fluent and high-performance User Interface.

**Comment by ramondeklein** [comment]
![image](https://cloud.githubusercontent.com/assets/6048186/12341381/80197d3e-bb21-11e5-9aa6-9df6b793abea.png)

**Comment by ramondeklein** [comment]
![image](https://cloud.githubusercontent.com/assets/6048186/12341484/55a41e1e-bb22-11e5-8787-88f1eb2694b1.png)

**Comment by lpolepeddi** [comment]
Thanks @ramondeklein! TransferXL is up on Made with Angular - https://www.madewithangular.com/#/sites/transferxl
