### ISSUE TITLE
Equity Reports

### ISSUE THREAD

**Issue by GustavoBMG** [madewithangular/madewithangular.github.io#97]
Hi,

Our website uses AngularJS v1.3.15.

http://equityreports.com.br/

Thanks,

Gustavo
![equityreports](https://cloud.githubusercontent.com/assets/16808092/12466463/fdedecf6-bfbb-11e5-9714-1e949bf39f6d.jpg)

**Comment by lpolepeddi** [comment]
Thanks @GustavoBMG! Equity Reports is up on Made with Angular https://www.madewithangular.com/#/sites/equity-reports

**Comment by GustavoBMG** [comment]
Thank you very much!

If it is not a problem or big issue, is it possible to classify it as a 'Finance' webapp?

Thanks again.
