### ISSUE TITLE
Add site roadzer.com

### ISSUE THREAD

**Issue by jorluiseptor** [madewithangular/madewithangular.github.io#99]

**Comment by jorluiseptor** [comment]
Screenshot

![roadzer-site-1280-711](https://cloud.githubusercontent.com/assets/4360992/12599911/a18662a2-c463-11e5-9bd5-898b2405e7bb.jpg)

**Comment by lpolepeddi** [comment]
Thanks! Roadzer is on Made with Angular https://www.madewithangular.com/#/sites/roadzer
